---
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Bug Report
description: File a bug report so we better understand how to fix it.
title: "bug(<scope>): <title>"
labels: ["bug"]
assignees:
  - aamkye
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report.
        Please fill out the following information about the bug you are reporting.
        Also please make sure that the `\<scope\>` and `\<title\>` in the title are correct.
        If you are not sure about anything, please ask @kocyba or @aamkye.

  # Why
  - type: textarea
    id: why-bug
    attributes:
      label: Why is this a bug?
      description: Please explain why certain behavior is a bug.
      placeholder: Ex. I need to be able to do X because Y.
    validations:
      required: true

  # What
  - type: textarea
    id: what-bug
    attributes:
      label: What is affected by this bug?
      description: Please explain what is affected by this bug.
      placeholder: Ex. supervision, sending messages, texter profiles.
    validations:
      required: true

  # Who
  - type: textarea
    id: who-bug
    attributes:
      label: Who is the bug affecting?
      description: Please explain who is the bug affecting.
      placeholder: Ex. All supervisors, Sally Supervisor, Level 1 CCs.
    validations:
      required: true

  # When
  - type: textarea
    id: when-bug
    attributes:
      label: When does this occur?
      description: Please explain when this bug occurs.
      placeholder: Ex. After ending a conversation, every night at 3pm, when I sign off.
    validations:
      required: true

  # Where
  - type: textarea
    id: where-bug
    attributes:
      label: Where on the platform does it happen?
      description: Please explain where on the platform does it happen.
      placeholder: Ex. In the a Supervisor chat box, on the conversation profile page, on the two-factor screen.
    validations:
      required: true

  # How
  - type: textarea
    id: how-bug
    attributes:
      label: How do we replicate the issue?
      description: Please explain how we replicate the issue.
      placeholder: Please be specific as possible. Use dashes (-) or numbers (1.) to create a list of steps.
    validations:
      required: true

  # Expected behavior (i.e. solution)
  - type: textarea
    id: expected-bug
    attributes:
      label: Expected behavior (i.e. solution)
      description: Please explain what should have happened.
    validations:
      required: true

  # Other Comments
  - type: textarea
    id: other-comments
    attributes:
      label: Other Comments / Logs
      description: Please explain anything else that you think is relevant.
